export const codes = [
  {
    title: "Players’ Code of Behaviour",
    items: [
      "Learn the Rules of Tee-ball and always play by them.",
      "Be a good sport. Applaud all good plays whether they be by your team or the opposition.",
      "Players must wear correct footwear, and hats and be suitably attired.",
      "Treat all players as you would like to be treated. Do not interfere with, bully or take unfair advantage of another player.",
      "Control your temper. Verbal abuse of officials or other players, deliberately distracting or provoking an opponent is not acceptable or permitted in any sport.",
      "Never argue with an Umpire, other players, Coaches or Officials. If you have a problem, discuss it with your Coach and allow them to take the necessary action.",
      "Verbal abuse and/or deliberate physical interference with opponents will not be tolerated by your Coach or Umpires and will result in immediate removal from the game as per TBAWA Rulebook.",
      "Strive to play to the best of your ability at all times, both at training and during games.",
      "Respect the time and efforts put in by your Coaches and Officials. They deserve your full support and commitment.",
      "Tee-ball is a team game. Encourage your teammates even when they make mistakes. Remember every player makes errors and has off days. Never ridicule opponents or teammates.",
      "Accept that at all times you will be required to take an equal turn on the bench. When on the bench, encourage your team and be prepared to play at all times.",
      "Respect your opponents and appreciate their good play. Without opposition, you would not be able to play the game of Tee-ball.",
      "Play for the fun of it and to improve your Tee-ball skills, not just to please parents and coaches.",
      "Respect the equipment provided for your use. Tee-ball equipment is very expensive and should be used responsibly. Abuse of equipment such as throwing helmets or bats is unacceptable.",
      "Always think of safety to avoid injuries to yourself and others.",
      "Foul language of any sort will not be tolerated.",
      "Players must still maintain their obligations to their club teams at both training and games.",
    ],
  },
  {
    title: "Parents’ Code of Behaviour",
    items: [
      "Children play Tee-ball for fun. Accept any mistakes as part of their learning process. Remember they are playing for their enjoyment, not yours.",
      "Encourage children to participate, do not force them.",
      "Don’t leave your child at Tee-ball. Stay and support the team, and volunteer to help and discuss your child’s progress with the coach.",
      "Focus on the child’s efforts and performance rather than winning or losing.",
      "Applaud good play from all teams. Applaud good plays by all teams.",
      "Encourage your child to always play within the Rules of Tee-ball and accept the Umpire’s decision.",
      "Never ridicule, abuse or yell at a child for making mistakes or losing a game.",
      "Offensive behaviour from parents or spectators is not acceptable under the Rules of Tee-ball and action will be taken against offenders.",
      "Recognize the value and importance of the volunteer coaches and officials. They give of their time and knowledge to provide organized Tee-ball for your child and deserve your respect and support.",
      "Tee-ball is a team game. Accept and understand that at all times your child may be asked to take a turn on the bench.",
      "Not all children can be champions. Do not force an unwilling child to participate in Tee-ball or expect more from your child than their best efforts.",
      "Respect official’s decisions and teach children to do likewise. Remember children learn best through example.",
      "If you disagree with an official or coach, raise the issue through the appropriate channels rather than question the person in public.",
      "Foul language of any sort will not be tolerated.",
      "Support and encourage all of the team, not only your child, and remember that the coach is there for the whole team and not individuals.",
      "As a commitment to training is essential, the coach must be advised if a player cannot attend a training session. It is important to note that training for State Teams often takes place throughout the Christmas break.",
      "Must advise the coach by the previous evening if their child is not going to be available through either injury or illness to enable changes to be implemented.",
      "Derisive comments aimed at the umpire or officials are unacceptable and only bring the club into disrepute.",
      "Show appreciation of volunteer coaches, umpires and officials. Without them, your child could not participate.",
      "Photography — parents please be mindful when taking photographs of your child that other parents may not wish for their child to be in your photos. If you wish to take videos of your child’s games, please contact the Woodlands Tee-Ball club for further clarification.",
    ],
  },
  {
    title: "Coaches’ Code of Behaviour",
    items: [
      "Be reasonable in your demands on young players’ time and energy.",
      "Always think about safety first.",
      "Ensure that equipment and facilities meet safety standards and are appropriate to the age and ability of the players.",
      "Avoid overplaying the talented player. Give all children equal opportunities to participate in all positions.",
      "Follow the advice of a Medical Practitioner/First Aid Officer when determining when an injured player is ready to recommence training or the game.",
      "Know the Rules of Tee-ball and ensure your players always play within those rules.",
      "Create opportunities to teach appropriate sports behaviour as well as basic skills.",
      "Develop team respect for opponents and officials. Do not abuse or ridicule players or officials and do not allow your players to do so.",
      "Ensure any discussions with umpires are kept below the level of argument. Remember your players look to you for example, how you accept a decision will be reflected in your players.",
      "No smoking or cigarettes on the diamond or bench.",
      "Discipline should be fair and consistent. Ensure your players know what is expected of them at training and during games.",
      "Do not tolerate players abusing equipment or misbehaving to the detriment of other players at any time.",
      "Keep yourself informed of sound coaching principles and seek more skilled advice when necessary.",
      "Remember your players are playing Tee-ball for their enjoyment. Endeavour to make the learning process both pleasurable and informative.",
      "Remember that players need a coach they can respect. Be generous with your praise when deserved and set a good example.",
      "Foul language of any sort will not be tolerated.",
      "No alcohol or cigarettes at training or any games.",
    ],
  },
  {
    title: "Officials’ Code of Behaviour",
    items: [
      "Compliment and encourage all participants. Give ALL children equal opportunities to participate.",
      "Ensure that rules, equipment, length of games and training schedules suit the age, ability and maturity level of the participants.",
      "Ensure that everyone involved in junior sport emphasizes fair play, not winning at all costs.",
      "Compliment and encourage all participants.",
      "Be consistent, objective and courteous when making decisions.",
      "Condemn unsporting behaviour and promote respect for all opponents.",
      "Emphasize the spirit of the game rather than the errors.",
      "Encourage and promote rule changes that will make participation more enjoyable.",
      "Be a good sport yourself. Actions speak louder than words.",
      "Keep up to date with the latest trends in officiating.",
      "Remember you set an example. Your behaviour and comments should be positive and supportive.",
    ],
  },
  {
    title: "Administrators’ Code of Behaviour",
    items: [
      "Give all children equal opportunities to participate.",
      "Ensure that rules, equipment, length of games and training schedules suit the age, ability and maturity level of participants.",
      "Provide quality supervision and instruction for junior players.",
      "Remember that children participate for enjoyment. Don’t overemphasize awards.",
      "Help coaches, umpires and officials highlight appropriate behaviour and skill development. Help improve the standards of coaching, umpiring and officiating.",
      "Keep up-to-date with the latest coaching practices and the principles of physical growth and development.",
      "Help children understand the differences between the junior competition they play and the professional sport.",
      "Ensure that everyone involved in junior sport emphasizes fair play, not winning at all costs.",
      "Give a code of behaviour sheet to spectators, officials, parents, coaches, umpires and players and encourage them to abide by it.",
      "Remember you set an example. Your behaviour and comments should be positive and supportive.",
      "Make children aware of the positive benefits of participation in sporting activities.",
      "Support the implementation of the National Junior Sport Policy.",
    ],
  },
  {
    title: "Spectators’ Code of Behaviour",
    items: [
      "Remember that children play sport for their enjoyment, not yours.",
      "Applaud good performance and efforts from each team. Congratulate all participants on their performance regardless of the game’s outcome.",
      "Respect official’s decisions and teach children to do the same.",
      "Never ridicule or scold a child for making a mistake. Positive comments are motivational.",
      "Condemn the use of violence in any form, be it by spectators, coaches, officials or players.",
      "Show respect for your team’s opponents. Without them, there would be no game.",
      "Encourage players to follow the rules and the officials’ decisions.",
      "Do not use foul language or harass players, coaches or officials.",
    ],
  },
] as const;
